# Generated by Django 5.0.1 on 2025-12-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("standards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QAReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_REVIEW", "En revisión"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                            ("CHANGES_REQUESTED", "Cambios solicitados"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("checklist_data", models.JSONField(default=dict)),
                ("is_blocking", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_reviews",
                        to="documents.document",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qa_reviews_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qa_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("IN_PROGRESS", "En progreso"),
                            ("RESOLVED", "Resuelto"),
                            ("WONT_FIX", "No se corregirá"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("section_reference", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="documents.document",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="validation.qareview",
                    ),
                ),
            ],
            options={
                "db_table": "document_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkpoint_name", models.CharField(max_length=255)),
                ("is_passed", models.BooleanField(default=False)),
                ("passed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="documents.document",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "validation_checkpoints",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("SECTION_EXISTS", "Sección existe"),
                            ("SECTION_NOT_EMPTY", "Sección no vacía"),
                            ("MIN_LENGTH", "Longitud mínima"),
                            ("MAX_LENGTH", "Longitud máxima"),
                            ("REGEX_MATCH", "Coincidencia regex"),
                            ("WORD_COUNT", "Conteo de palabras"),
                            ("COHERENCE", "Coherencia con historias"),
                            ("TRACEABILITY", "Trazabilidad"),
                            ("FORMAT_CHECK", "Verificación de formato"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Información"),
                            ("WARNING", "Advertencia"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="ERROR",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("validation_logic", models.JSONField(default=dict)),
                ("error_message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documentation_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="standards.documentationstandard",
                    ),
                ),
            ],
            options={
                "db_table": "validation_rules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASSED", "Aprobado"),
                            ("FAILED", "Fallido"),
                            ("WARNING", "Advertencia"),
                            ("SKIPPED", "Omitido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="documents.document",
                    ),
                ),
                (
                    "validation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="validation.validationrule",
                    ),
                ),
            ],
            options={
                "db_table": "validation_results",
                "ordering": ["-validated_at"],
            },
        ),
    ]
