# Generated by Django 5.0.1 on 2025-12-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockingIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Menor"),
                            ("MAJOR", "Mayor"),
                            ("CRITICAL", "Crítico"),
                            ("BLOCKER", "Bloqueante"),
                        ],
                        default="MAJOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("IN_PROGRESS", "En progreso"),
                            ("RESOLVED", "Resuelto"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blocking_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("STORIES_CLOSED", "Historias cerradas"),
                            ("DOCUMENTATION_APPROVED", "Documentación aprobada"),
                            ("QA_VALIDATED", "QA validado"),
                            ("DELIVERY_DOCUMENT", "Acta de entrega"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En progreso"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                            ("NA", "No aplica"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("validation_criteria", models.JSONField(default=dict)),
                ("validation_result", models.JSONField(default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "checklist_items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("project_type", models.CharField(blank=True, max_length=100)),
                ("template_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "checklist_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("certificate_date", models.DateTimeField(auto_now_add=True)),
                ("project_summary", models.TextField()),
                ("deliverables", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=dict)),
                ("signatures", models.JSONField(default=dict)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("is_final", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "delivery_certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "En progreso"),
                            ("COMPLETED", "Completado"),
                            ("BLOCKED", "Bloqueado"),
                            ("CERTIFIED", "Certificado"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_certified", models.BooleanField(default=False)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "delivery_checklists",
            },
        ),
    ]
