# Generated by Django 5.0.1 on 2025-12-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("context", models.JSONField(default=dict)),
                ("generated_content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En progreso"),
                            ("SUCCESS", "Exitoso"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "execution_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_generation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("prompt_template", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmbeddedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("embedding_vector", models.JSONField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "embedded_documents",
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="RAGConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinecone_index_name", models.CharField(blank=True, max_length=255)),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-ada-002", max_length=100),
                ),
                ("llm_model", models.CharField(default="gpt-4", max_length=100)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("max_tokens", models.IntegerField(default=2000)),
                ("chunk_size", models.IntegerField(default=1000)),
                ("chunk_overlap", models.IntegerField(default=200)),
                ("top_k_results", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rag_configurations",
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Muy malo"),
                            (2, "Malo"),
                            (3, "Regular"),
                            (4, "Bueno"),
                            (5, "Excelente"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("was_useful", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
