# Generated by Django 5.0.1 on 2025-12-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_engine", "0002_initial"),
        ("standards", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="documentation_standard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="standards.documentationstandard",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aifeedback",
            name="generation_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="ai_engine.aigenerationlog",
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="documentation_standard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_templates",
                to="standards.documentationstandard",
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_templates",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="embeddeddocument",
            name="documentation_example",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="standards.documentationexample",
            ),
        ),
        migrations.AddField(
            model_name="embeddeddocument",
            name="documentation_standard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="standards.documentationstandard",
            ),
        ),
        migrations.AddField(
            model_name="embeddeddocument",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedded_documents",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="ragconfiguration",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_config",
                to="users.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="embeddeddocument",
            index=models.Index(
                fields=["organization", "documentation_standard"],
                name="embedded_do_organiz_07fe46_idx",
            ),
        ),
    ]
