# Generated by Django 5.0.1 on 2025-12-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=100)),
                ("resource_name", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Documento"),
                            ("USER_STORY", "Historia de usuario"),
                            ("QA_REVIEW", "Revisión QA"),
                            ("DELIVERY", "Entrega"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.CharField(max_length=100)),
                ("resource_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_history",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("READ", "Leer"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                            ("APPROVE", "Aprobar"),
                            ("REJECT", "Rechazar"),
                            ("EXPORT", "Exportar"),
                            ("IMPORT", "Importar"),
                            ("LOGIN", "Iniciar sesión"),
                            ("LOGOUT", "Cerrar sesión"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(max_length=100)),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_data", models.JSONField(default=dict)),
                ("response_data", models.JSONField(default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("ISO27001", "ISO 27001"),
                            ("SOC2", "SOC 2"),
                            ("GDPR", "GDPR"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "Generando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                ("report_data", models.JSONField(default=dict)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_reports/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "compliance_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=100)),
                ("retention_days", models.IntegerField()),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_retention_policies",
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGIN", "Intento de login fallido"),
                            ("UNAUTHORIZED_ACCESS", "Acceso no autorizado"),
                            ("PERMISSION_DENIED", "Permiso denegado"),
                            ("DATA_EXPORT", "Exportación de datos"),
                            ("SUSPICIOUS_ACTIVITY", "Actividad sospechosa"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Baja"),
                            ("MEDIUM", "Media"),
                            ("HIGH", "Alta"),
                            ("CRITICAL", "Crítica"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
