# Generated by Django 5.0.1 on 2025-12-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_workspace_document_workspace"),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
            ),
        ),
    ]
