# Generated by Django 5.0.1 on 2025-12-29 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_make_project_optional"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TECHNICAL", "Documentación Técnica"),
                    ("PROCESSES", "Procesos"),
                    ("GUIDES", "Guías"),
                    ("KNOWLEDGE_BASE", "Base de Conocimiento"),
                ],
                help_text="Tipo legacy - usar workspace_type en su lugar",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Clave única del tipo (ej: TECHNICAL, CUSTOM_TYPE)",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nombre visible del tipo (ej: Documentación Técnica)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del propósito y uso de este tipo de espacio",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="Folder",
                        help_text="Nombre del icono Material-UI",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea",
                        help_text="Color en formato hexadecimal",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Los tipos de sistema no pueden ser eliminados",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workspace_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organización propietaria. Si es null, el tipo es global/predeterminado.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_types",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_types",
                "ordering": ["order", "label"],
                "unique_together": {("organization", "key")},
            },
        ),
        migrations.AddField(
            model_name="workspace",
            name="workspace_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de workspace (nueva implementación)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workspaces",
                to="documents.workspacetype",
            ),
        ),
    ]
