# Generated by Django 5.0.1 on 2025-12-29 06:02

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    """Convierte DRAFT y AI_GENERATED a IN_REVIEW."""
    Document = apps.get_model('documents', 'Document')
    Document.objects.filter(status__in=['DRAFT', 'AI_GENERATED']).update(status='IN_REVIEW')


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_alter_workspace_type_workspacetype_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_old_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_REVIEW", "En revisión"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="IN_REVIEW",
                max_length=20,
            ),
        ),
    ]
