# Generated by Django 5.0.1 on 2025-12-29 06:05

from django.db import migrations, models


def translate_statuses(apps, schema_editor):
    """Convierte los estados de inglés a español."""
    Document = apps.get_model('documents', 'Document')

    # Mapeo de estados en inglés a español
    status_mapping = {
        'IN_REVIEW': 'EN_REVISION',
        'APPROVED': 'APROBADO',
        'REJECTED': 'RECHAZADO',
    }

    for old_status, new_status in status_mapping.items():
        Document.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_draft_ai_generated_status"),
    ]

    operations = [
        migrations.RunPython(translate_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_REVISION", "En revisión"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="EN_REVISION",
                max_length=20,
            ),
        ),
    ]
