# Generated by Django 5.0.1 on 2026-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_translate_status_to_spanish"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
