# Generated by Django 5.0.1 on 2025-12-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del estándar (ej: Casos de Uso)",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USE_CASE", "Casos de Uso"),
                            ("UML_DIAGRAM", "Diagramas UML"),
                            ("API_REST", "APIs REST"),
                            ("DATABASE", "Base de Datos"),
                            ("ARCHITECTURE", "Arquitectura"),
                            ("USER_MANUAL", "Manual de Usuario"),
                            ("TECHNICAL_SPEC", "Especificación Técnica"),
                            ("TEST_PLAN", "Plan de Pruebas"),
                            ("DEPLOYMENT", "Despliegue"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción de qué tipo de documentación cubre este estándar"
                    ),
                ),
                ("icon", models.CharField(blank=True, default="📄", max_length=50)),
                ("color", models.CharField(default="#667eea", max_length=7)),
                (
                    "ai_prompt_template",
                    models.TextField(
                        blank=True,
                        help_text="Plantilla de prompt para generación con IA. Usa {input} para el texto del usuario.",
                    ),
                ),
                (
                    "requires_diagram",
                    models.BooleanField(
                        default=False,
                        help_text="¿Este estándar genera diagramas visuales?",
                    ),
                ),
                (
                    "diagram_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MERMAID", "Mermaid"),
                            ("PLANTUML", "PlantUML"),
                            ("DRAWIO", "Draw.io"),
                            ("IMAGE", "Imagen"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_standards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estándar de Documentación",
                "verbose_name_plural": "Estándares de Documentación",
                "db_table": "documentation_standards",
                "ordering": ["category", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="DocumentationExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título descriptivo del ejemplo (ej: Login de Usuario)",
                        max_length=255,
                    ),
                ),
                (
                    "input_prompt",
                    models.TextField(
                        help_text="Enunciado/descripción que el usuario proporciona para generar la documentación"
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(
                        help_text="Contenido del documento generado (texto, markdown, etc.)"
                    ),
                ),
                (
                    "diagram_code",
                    models.TextField(
                        blank=True,
                        help_text="Código del diagrama (Mermaid, PlantUML, etc.) si aplica",
                    ),
                ),
                (
                    "diagram_image",
                    models.FileField(
                        blank=True,
                        help_text="Imagen del diagrama renderizado",
                        null=True,
                        upload_to="examples/diagrams/",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separados por comas para búsqueda (ej: autenticación, login, seguridad)",
                        max_length=255,
                    ),
                ),
                (
                    "complexity_level",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Simple"),
                            ("MEDIUM", "Medio"),
                            ("COMPLEX", "Complejo"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Orden de aparición"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="¿Mostrar como ejemplo destacado?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_examples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="standards.documentationstandard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejemplo de Documentación",
                "verbose_name_plural": "Ejemplos de Documentación",
                "db_table": "documentation_examples",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        help_text="Enunciado que el usuario proporciona (ej: 'Sistema de login con email y contraseña')"
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(
                        blank=True, help_text="Contenido generado por la IA"
                    ),
                ),
                (
                    "generated_diagram_code",
                    models.TextField(
                        blank=True, help_text="Código del diagrama generado (si aplica)"
                    ),
                ),
                (
                    "generated_diagram_image",
                    models.FileField(
                        blank=True,
                        help_text="Imagen del diagrama renderizado",
                        null=True,
                        upload_to="ai_tests/diagrams/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("COMPLETED", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        blank=True,
                        help_text="Modelo de IA utilizado (ej: gpt-4, claude-3, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "generation_time_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Tiempo que tardó la generación en segundos",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Calificación del usuario (1-5)",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del usuario sobre la generación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tests",
                        to="standards.documentationstandard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba de Generación IA",
                "verbose_name_plural": "Pruebas de Generación IA",
                "db_table": "ai_generation_tests",
                "ordering": ["-created_at"],
            },
        ),
    ]
