# Generated by Django 5.0.1 on 2025-12-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentationstandard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentationstandard',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización propietaria. Si es null, el estándar es global/predeterminado para todas las organizaciones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='users.organization'),
        ),
    ]
